# schema.yml

 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     description: raw data from exercice 3 Le Wagon
     tables:
       - name: sales
         identifier : raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: "CAST (date_date AS TIMESTAMP)"
         freshness:
            warn_after:
              count: 90
              period: day
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: number of the order
           - name: products_id
             description: number of the product
           - name: revenue
             description: price of the order
           - name: quantity
             description: number of product in the order
       - name: product
         tests:
           - unique:
               column_name: products_id
           - not_null:
               column_name: products_id
         identifier : raw_gz_product
         description: product of Greenweez / we have on row per product_id found in each purchase_price
         columns:
           - name: products_id
             description: number of the product
           - name: purchase_price
             description: buy cost of the product
       - name: ship
         tests:
           - unique:
               column_name: orders_id
           - not_null:
               column_name: orders_id
         identifier : raw_gz_ship
         description: ship of Greenweez / we have on row with orders_id, shipping_fee, logcost and ship_cost
         columns:
           - name: orders_id
             description: number of the order
           - name: shipping_fee
             description: fee on shipping from Greenweez to customer paid by the customer
           - name: logcost
             description: logistical cost of the order
           - name: ship_cost
             description: cost from the seller to Greenweez paid by Greenweez
       - name: adwords
         identifier: raw_gz_adwords
         description: ad campaign on adwords
         columns:
           - name: date_date
             description: date of each campaign
           - name: paid_source
             description: origin of the campaign
           - name: campaign_key
             description: campaign number
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: cost of the ads
           - name: impressions
             description: number of views
           - name: clicks
             description: number of clicks

       - name: bing
         identifier: raw_gz_bing
         description: ad campaign on bing
         columns:
           - name: date_date
             description: date of each campaign
           - name: paid_source
             description: origin of the campaign
           - name: campaign_key
             description: campaign number
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: cost of the ads
           - name: impressions
             description: number of views
           - name: clicks
             description: number of clicks

       - name: criteo
         identifier: raw_gz_criteo
         description: ad campaign on criteo
         columns:
           - name: date_date
             description: date of each campaign
           - name: paid_source
             description: origin of the campaign
           - name: campaign_key
             description: campaign number
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: cost of the ads
           - name: impressions
             description: number of views
           - name: clicks
             description: number of clicks

       - name: facebook
         identifier: raw_gz_facebook
         description: ad campaign on facebook
         columns:
           - name: date_date
             description: date of each campaign
           - name: paid_source
             description: origin of the campaign
           - name: campaign_key
             description: campaign number
           - name: camPGN_name
             description: name of the campaign
           - name: ads_cost
             description: cost of the ads
           - name: impressions
             description: number of views
           - name: clicks
             description: number of clicks

 models:
   - name: int_orders_margin
     description: model with revenue, quantity and purchase_cost calculations
     columns:
       - name: orders_id
         description: unique number of the order
       - name: data_date
         description: date of the order
       - name: products_id
         description: unique number of the product
       - name: revenue
         description: revenue of the order
       - name: quantity
         description: quantity of products in the order
       - name: purchase_cost
         description: it is the quantity multiplied by the purchase_price
       - name: margin
         description: it is the revenue - purchase_cost

   - name: int_orders_operational
     description: model with operational margin calculations
     columns:
       - name: operational_margin
         description: it is the margin + shipping_fee - logcost - ship_cost

   - name: int_sales_margin
     description: model with the calculations of the purchase_cost and margin
     columns:
       - name: purchase_cost
         description: it is quantity multiplied with the purchase_price
       - name: margin
         description: it is the revenue - purchase_cost

   - name: finance_days
     description: model updated everyday with total_number_of_transactions, total_revenue, average_basket, total_operational_margin, total_purchase_cost, total_shipping_fee, total_logcost, total_quantity_of_products_sold
     columns:
       - name: total_number_of_transactions
         description: sum of transactions of the day
       - name: total_revenue
         description: sum of revenue of the day
       - name: average_basket
         description: average_basket of the day
       - name: total_operational_margin
         description: sum of operational_margin
       - name: total_purchase_cost
         description: sum purchase_cost